-- MySQL Script generated by MySQL Workbench
-- Fri Jul  5 12:35:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cecytevlocationdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cecytevlocationdb` ;

-- -----------------------------------------------------
-- Schema cecytevlocationdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cecytevlocationdb` DEFAULT CHARACTER SET utf8 ;
USE `cecytevlocationdb` ;

-- -----------------------------------------------------
-- Table `cecytevlocationdb`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cecytevlocationdb`.`students` ;

CREATE TABLE IF NOT EXISTS `cecytevlocationdb`.`students` (
  `idStudent` VARCHAR(20) NOT NULL,
  `nameStudent` VARCHAR(45) NULL,
  `lastNameStudent` VARCHAR(45) NULL,
  `year` VARCHAR(1) NULL,
  `passwordStudent` VARCHAR(45) NULL,
  `telephoneTutor` VARCHAR(45) NULL,
  PRIMARY KEY (`idStudent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cecytevlocationdb`.`teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cecytevlocationdb`.`teachers` ;

CREATE TABLE IF NOT EXISTS `cecytevlocationdb`.`teachers` (
  `idTeacher` VARCHAR(20) NOT NULL,
  `nameTeacher` VARCHAR(45) NULL,
  `lastnameTeacher` VARCHAR(45) NULL,
  `passwordTeacher` VARCHAR(45) NULL,
  PRIMARY KEY (`idTeacher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cecytevlocationdb`.`attendances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cecytevlocationdb`.`attendances` ;

CREATE TABLE IF NOT EXISTS `cecytevlocationdb`.`attendances` (
  `idattendances` VARCHAR(45) NOT NULL,
  `dateAttendance` DATETIME NULL,
  `typeAttendance` TINYINT NULL,
  `students_idStudent` VARCHAR(20) NOT NULL,
  `teachers_idTeacher` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idattendances`),
  INDEX `fk_attendances_students1_idx` (`students_idStudent` ASC) VISIBLE,
  INDEX `fk_attendances_teachers1_idx` (`teachers_idTeacher` ASC) VISIBLE,
  CONSTRAINT `fk_attendances_students1`
    FOREIGN KEY (`students_idStudent`)
    REFERENCES `cecytevlocationdb`.`students` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attendances_teachers1`
    FOREIGN KEY (`teachers_idTeacher`)
    REFERENCES `cecytevlocationdb`.`teachers` (`idTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cecytevlocationdb`.`locationStudents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cecytevlocationdb`.`locationStudents` ;

CREATE TABLE IF NOT EXISTS `cecytevlocationdb`.`locationStudents` (
  `DateLocation` DATETIME NOT NULL,
  `latitudeStudent` VARCHAR(45) NULL,
  `longitudeStudent` VARCHAR(45) NULL,
  `students_idStudent` VARCHAR(20) NOT NULL,
  `idLocationStudent` VARCHAR(45) NOT NULL,
  INDEX `fk_locationStudents_students1_idx` (`students_idStudent` ASC) VISIBLE,
  PRIMARY KEY (`idLocationStudent`),
  CONSTRAINT `fk_locationStudents_students1`
    FOREIGN KEY (`students_idStudent`)
    REFERENCES `cecytevlocationdb`.`students` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
